version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.3.7"

phases:
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ## S3 WEBSITE DEPLOY : Starting ...."
      - "aws s3 sync dist $S3_BUCKET"

artifacts:
  files:
    - '**/*'